color0: #25282c
color1: #ffb0cd
color2: #aad291
color3: #edc06c
color4: #a6c8ff
color5: #e0b8f6
color6: #89d6b9
color7: #ecd7db
color8: #9d8c90
color9: #ffd9e4
color10: #c5efa7
color11: #ffdea7
color12: #d5e3ff
color13: #f4daff
color14: #a4f2d5
color15: #e0e2e8
background: #25282c
foreground: #e0e2e8
cursor: #ffb0cd
