color0: #1c2024
color1: #ffb0cd
color2: #a9d291
color3: #ecc06c
color4: #a7c8ff
color5: #e0b8f6
color6: #88d6ba
color7: #c0c7cd
color8: #41484d
color9: #ffd9e4
color10: #c5efa7
color11: #ffdea4
color12: #d5e3ff
color13: #f4d9ff
color14: #a4f2d6
color15: #e0e2e8
background: #1c2024
foreground: #e0e2e8
cursor: #ffb0cd
