color0: {{ansi.blk}}
color1: {{ansi.red}}
color2: {{ansi.grn}}
color3: {{ansi.yel}}
color4: {{ansi.blu}}
color5: {{ansi.mag}}
color6: {{ansi.cya}}
color7: {{ansi.wht}}
color8: {{ansi.gra}}
color9: {{ansi.rrd}}
color10: {{ansi.ggn}}
color11: {{ansi.yyl}}
color12: {{ansi.bbl}}
color13: {{ansi.mmg}}
color14: {{ansi.ccy}}
color15: {{ansi.wwt}}
background: {{tm.background}}
foreground: {{tm.foreground}}
cursor: {{tm.caret}}
